# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f576f916ff981d73b89bc508f25b99d76b9d173f98ee54c870d34d3ec2fc4cda035fa8b5cd1c5bc3fc89c3887f306e4426696d584a784fa1639b6bd43dad317

test:
  secret_key_base: 193d93f7b760596a7089e392cc474a290ca60066455294e0118450335ecda64df87e54c12e56bf8876b9d8b0036660df3945e2430aeedcf35e1377233a24031f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
